Testing improved, commitlint removed

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,4 +1,4 @@
-name: NPM Package Publish
+name: Create Release
 
 on:
   push:
@@ -40,22 +40,46 @@ jobs:
       - name: Run Build
         run: yarn build
 
-      - name: Upload Test Coverage
-        uses: codecov/codecov-action@v1
-        with:
-          fail_ci_if_error: true
+      - name: Check if version has been updated
+        id: check
+        uses: EndBug/version-check@v1
 
-      - name: Semantic Release
-        uses: cycjimmy/semantic-release-action@v2
-        id: semantic
+      # NOTE: Not Currently publishing to npm
+      # - name: Publish
+      #   if: steps.check.outputs.changed == 'true'
+      #   env:
+      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+      #     GITHUB_REF: ${{ github.ref }}
+      #   run: |
+      #     gitBranch=${GITHUB_REF##*/}
+      #     packageVersion=$(cat package.json | jq -r '.version')
+      #     publishFlag=$(if [ "$GITHUB_REF" != 'refs/heads/master' ]; then eval echo '--tag $gitBranch'; else echo ''; fi;)
+      #     echo "::set-env name=PACKAGE_VERSION::$packageVersion"
+      #     npm publish $publishFlag
+
+      # Upload to codecov.io. Curl used in place of codecov/codecov-action
+      # due to long build time. See https://github.com/codecov/codecov-action/issues/21
+      - name: Upload Coverage
+        if: steps.check.outputs.changed == 'true'
+        run: bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
+
+      - name: Create Release
+        if: steps.check.outputs.changed == 'true'
+        id: create_release
+        uses: actions/create-release@latest
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+          GITHUB_TOKEN: ${{ github.token }}
+        with:
+          tag_name: v${{ env.PACKAGE_VERSION }}
+          release_name: v${{ env.PACKAGE_VERSION }}
+          draft: false
+          prerelease: github.ref != 'refs/heads/master'
 
       - name: Updates Major Version Branch
         # If a new version is published, i.e. v1.2.3 then this step will update branch "v1" to this commit
-        if: steps.semantic.outputs.new_release_published == 'true'
+        if: steps.check.outputs.changed == 'true'
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ github.token }}
         run: |
-          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v${{steps.semantic.outputs.new_release_major_version}} 
+          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v${PACKAGE_VERSION}
+  
